### ISSUE TITLE
OBO queries (12/5/22)

### ISSUE THREAD

**Issue by ColmMassey** [SolidarityEconomyAssociation/owned-by-oxford-project#16]
1. -  If an organisation doesn't have a postcode but is located or works in a specific area what's the best way to ensure that it appears on the map in the correct location? For OCA it currently appears in central Oxford
2.  - Why is the ref  `${labels.noLocation}`
3.  - How much scope is there to edit the info on the pop up for each organisation? 
4.  - Why does it say "activites (modified)" on the pop up info?

**Comment by ColmMassey** [comment]
1- My understanding is that if no address or postcode is provided, it will be positioned to a default location that we specify in the config, and it is central oxford atm. It is fine to specify a lon lat that is a park, say, and it should be positioned there. I expect that will create a dialog border with a little pointer to that point, so may suggest to viewers that that is its location.

2 - Can you comment why that appears @wu-lee ?

3 - At the moment, it is hard wired to the organisation's name. What would it take to point to another available field?

4 - That is the name of the standard vocabulary we use here. Can we see if it is actually hardcoded in the Dialog atm or as it should be, derived from the standard specifications?

**Comment by ColmMassey** [comment]
1 - just needs testing
2 - Bug fix
3  - Calarify if it is tool tip or dialog - if dialog we can dsiplay anything which has been brought through from Airtable
4  - We can change the title of ativities to suit her needs - 
4 -a - at some point deprecte Activities

**Comment by ColmMassey** [comment]
1 - I tested the hypothesis, and my hunch seems to be right. Having no address and postcode means it considers the initiative to have no location data and italicises it in the directory and places it in the default centre of the map used for all locationless entities. It ignores the manually specified Lat and Lon.

**Comment by ColmMassey** [comment]
So I think we need to look at how the map logic works, so that it will use the lat lon even when no address has been specified.

**Comment by ColmMassey** [comment]
Even when I put a fake address in for SEA in the Airtable, it doesn't seem to be getting through. Needs closer look.

**Comment by ColmMassey** [comment]
> * Why does it say "activites (modified)" on the pop up info?

Are we able to change this now?

**Comment by wu-lee** [comment]
I've updated the custom popup code to show "Main Activity", ignoring the localised label, since ObO will not be localised.

We can decide if we want to update the vocab itself as a separate step.

**Comment by wu-lee** [comment]
From Anna's email:
- Point 1 - re: where do non-located organisations show.  The default location thing is fixed now, I believe.
- Point 2 - Why is the ref ${labels.noLocation} - this is fixed.
- Point 3 - scope for editing - we have our proposal for linking tables and overriding fields. This seems to work for designated fields.
- Point 4 - "activites (modified)" - can be fixed in two ways, as mentioned I have used a. for now
  a. by altering the custom popup.js (may be sufficient for ObO, which has no localisation)
  b. by updating the vocab itself (more delicate, all our maps will have the new label)

All this has been deployed to the obo-public site for demonstration, and Anna and Simon have been updated in a meeting yesterday. They seem happy.
