### ISSUE TITLE
Airtable fields not getting updated in ObO public map. 

### ISSUE THREAD

**Issue by ColmDC** [SolidarityEconomyAssociation/owned-by-oxford-project#19]
**Describe the bug**
Report from ObO team: I’ve been finding some issues with the updating. Some of the changes to fields I’ve updated have appeared, but many haven’t even after a day. I’ve tried different ways of refreshing and entering new data but can’t work it out. I’ve added a new field in the Airtable called “map notes” in the “Organisations ObO” grid so have a look at that for more detail.
 
One issue that seems to be consistent is that the ObO field secondary activities are not appearing. Secondary activities only appear when they have come from an external data source.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ColmDC** [comment]
From @wu-lee:
There are some errors in the data pipeline which would explain why the 
map data isn't updating - these have been occurring since about mid-day 
yesterday.

I'm investigating what's causing it...

**Comment by wu-lee** [comment]
The problem which broke the pipeline is a quoting bug, which means that rows with addresses including single quotes like "St Leonard's" can't be unambiguously extracted from the CSV data, because the apostrophe is interpreted as a quote and this results in invalid data.

This shouldn't happen, but fixing it requires regenerating the external initiatives table, which is also not working due to shifts in the Co-op UK data source, so attempting to fix/work around that at the moment.

**Comment by wu-lee** [comment]
Current workaround is to:
- override the "St Leonard's" Street Address field for Headington Fairtrade Co-op in the Organisations airtable to one without an apostrophe
- likewise remove the double link to External Initiatives table for The Children's Allotment
- fix the `converter` script so that it knows which fields are multi-valued and quotes accordingly

This seems to work for now, but the `airtable-import` script still  needs fixing to rectify the underlying issue then the alteration in the first point above reverted.

**Comment by ColmDC** [comment]
The workaround has got the pipeline flowing again, so closing this, but made a ticket here, for proper fix to be addressed later. https://github.com/DigitalCommons/owned-by-oxford-project/issues/20
